<div class="ftp_settings_block" style="display:none;">

<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('Base URL', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <?php $tpl->displayTextfield($this, 'baseUrl-ftp', 'http://mystaticsite.com', '', ''); ?>

    <p><em><?php echo __("Set this to the URL you intend to host your static exported site on, ie http://mystaticsite.com. Do not set this to the same URL as the WordPress site you're currently using (the address in your browser above). This plugin will rewrite all URLs in the exported static html from your current WordPress URL to what you set here. Supports http, https and protocol relative URLs.", 'static-html-output-plugin');?></em></p> 
  </div>
</section>

<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('FTP Server', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <?php $tpl->displayTextfield($this, 'ftpServer', '198.176.1.23', ''); ?>
  </div>
</section>

<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('FTP Port', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <?php $tpl->displayTextfield($this, 'ftpPort', '21', ''); ?>
  </div>
</section>

<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('FTP Username', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <?php $tpl->displayTextfield($this, 'ftpUsername', 'FTP Username', ''); ?>
  </div>
</section>
          
<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('FTP Password', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <?php $tpl->displayTextfield($this, 'ftpPassword', 'FTP Password', '', 'password'); ?>
  </div>
</section>
    
<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('FTP Remote Path', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <?php $tpl->displayTextfield($this, 'ftpRemotePath', 'FTP Remote Path', 'will attempt to create folder recursively if non-existent'); ?>
  </div>
</section>

<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('Use FTPS (TLS)', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <?php $tpl->displayCheckbox($this, 'ftpTLS', 'Use FTP with TLS'); ?>
  </div>
</section>

<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('Use active FTP', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <?php $tpl->displayCheckbox($this, 'useActiveFTP', 'Use active FTP (defaults to passive mode) <a href="https://stackoverflow.com/q/1699145/1668057" target="_blank">What\'s the difference?</a>'); ?>
  </div>
</section>

<section class="wp2static-content wp2static-flex">
  <div class="content" style="max-width:30%">
    <h2><?php echo __('Test FTP Credentials', 'static-html-output-plugin');?></h2>
  </div>

  <div class="content">
    <button id="ftp-test-button" type="button" class="wp2static-btn btn-sm">Test FTP Settings</button>

    <div class="spinner is-active" style="float:none;width:auto;height:auto;padding:10px 0 10px 50px;;"> </div>
  </div>
</section>

</div>
